.TH GENPKG 1 2012-5-31
.SH NAME
genpkg \- ArchLinux package meta generator
.SH SYNOPSIS
.B genpkg
[
.B names of packages to generate
]
.SH DESCRIPTION
.PP
If PKGBUILDs are binary package generators, then \fBgenpkg\fR is a package
generator generator. \fBgenpkg\fR creates PKGBUILDs and supporting files that
can be used to create source packages or build binary packages. The purpose
of \fBgenpkg\fR is to more easily automate the creation of packages. The
primary goal is to map packages from other sources of software releases.
.PP
Software releases include perl's CPAN distributions, python's
PyPI eggs, or ruby's gems. In order to meet my current needs,
\fBgenpkg\fR currently supports perl CPAN distributions. The design
should make it easy to add support for any other such sources. \fBgenpkg\fR
is merely the front to several other scripts which are responsible for the
different stages of package generation.
.SH FILES
.PP
The following directories are used by genpkg, by default. Right now it
is only possible to change them by editing genpkg. They are at the top of
the script.
.IP \fB$HOME/pkg/dest/\fR
Generated packages are stored here
.IP \fB$HOME/pkg/mods/\fR
Modifications are searched for in this directory.
.IP \fB$HOME/.genpkg/preps/\fR
Preparation scripts are searched for here. Each script may have a
supporting directory as well.
.IP \fB$HOME/.genpkg/var/\fR
Data that needs to be saved between invocations by preparation
scripts is stored here. These are usually indices of releases.
.SH SEE ALSO
.PP
.BR prepkg (1),
.BR modpkg (1),
.BR pbfields (1),
.BR injectdigs(1),
.BR vervar (1),
.BR putpkgtree (1),
.BR getpkgtree (1),
.BR PKGDATA (5)
.SH AUTHOR
.PP
Justin "juster" Davis <jrcd83@gmail.com>
