#!/bin/sh

set -e
umask 022
prog=setup
binfiles='genpkg prepkg modpkg pbfields putpkgtree getpkgtree
	injectdigs vervar'
preps='perl perl.d/
	perl.d/fetchcpan perl.d/perl-dist perl.d/perl-pkgbuild'

md()
{
	d="$1"
	case "$d" in
	'')	return 1 ;;
	*/)	;;
	*)	d="$d/" # mostly for pretty printing
	esac
	[ -d "$d" ] || mkdir -p "$d"
	echo "$d"
}

ins()
{
	case "$1" in
	*/)	md "$2/$1" ;;
	*)	install -m 755 "$1" "$2/$1"
		echo "$2/$1"
	esac
}

case "$1" in
'')	cat <<EOF 1>&2
Run "$prog genpkg" to install genpkg & friends into ~/genpkg and ~/bin.
Run "$prog mods" to install mods into ~/pkg/mods.
EOF
	;;
genpkg)
	md ~/bin
	for pkg in $binfiles
	do
		ins "bin/$pkg" ~
	done

	md ~/.genpkg
	md ~/.genpkg/preps
	for p in $preps
	do
		ins "preps/$p" ~/.genpkg
	done
	md ~/.genpkg/var

	dst=~/.genpkg/var/perlcore.mods
	install -m644 misc/perlcore.mods-5.16.0 $dst
	echo $dst

	md ~/pkg/dest
	;;
mods)
	md ~/pkg/mods/
	for m in mods/*
	do
		cp "$m" ~/pkg/"$m"
		echo ~/pkg/"$m"
	done
	;;
*)	echo "$prog: unrecognized argument: $1" 1>&2
	exit 1
esac

exit 0
